import type { Exercise } from '@/types/exercise'

type Q = Exercise
const mk = (q: Q): Q => q

export const EXERCISE_POOL: Exercise[] = [
  // g3-sum-multiple 和倍问题
  mk({ id: 'sum-m-01', knowledgePoints: ['g3-sum-multiple'], type: 'choice', difficulty: 1,
    stem: '两数之和为36，大数是小数的3倍。小数是？', options: ['6','9','12','27'], answer: '1',
    solution: [{ description: '小数=36÷(3+1)=9' }], hints: ['总段数=1+3=4','小数=和÷(倍数+1)'],
    commonMistakes: [{ mistake: '36÷3=12', reason: '忘记+1', correction: '36÷4=9', errorLayer: 'L2' }],
    irtParams: { a: 1, b: -1, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'sum-m-02', knowledgePoints: ['g3-sum-multiple'], type: 'fill', difficulty: 2,
    stem: '苹果和梨共80个，苹果是梨的4倍。梨___个，苹果___个。', answer: '16',
    solution: [{ description: '梨=80÷5=16，苹果=64' }], hints: ['总段数=5','每段=16'],
    commonMistakes: [{ mistake: '80÷4=20', reason: '忘记+1', correction: '80÷5=16', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'sum-m-03', knowledgePoints: ['g3-sum-multiple'], type: 'fill', difficulty: 3,
    stem: '甲是乙的2倍，丙是甲的3倍，三数之和为99。乙=___。', answer: '11',
    solution: [{ description: '乙1段，甲2段，丙6段；乙=99÷9=11' }], hints: ['设乙为1段','共1+2+6=9段'],
    commonMistakes: [{ mistake: '99÷(2+3+1)=16.5', reason: '倍数关系理解错误', correction: '99÷9=11', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1, c: 0.2 }, estimatedTime: 120 }),
  // g3-diff-multiple 差倍问题
  mk({ id: 'diff-m-01', knowledgePoints: ['g3-diff-multiple'], type: 'choice', difficulty: 1,
    stem: '两数之差为24，大数是小数的4倍。小数是？', options: ['6','8','12','32'], answer: '1',
    solution: [{ description: '小数=24÷(4-1)=8' }], hints: ['差对应4-1=3段','每段=24÷3=8'],
    commonMistakes: [{ mistake: '24÷4=6', reason: '未用倍数-1', correction: '24÷3=8', errorLayer: 'L2' }],
    irtParams: { a: 1, b: -0.5, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'diff-m-02', knowledgePoints: ['g3-diff-multiple'], type: 'fill', difficulty: 2,
    stem: '哥比弟多45元，哥的钱是弟的6倍。弟有___元。', answer: '9',
    solution: [{ description: '弟=45÷5=9' }], hints: ['差对应6-1=5段'],
    commonMistakes: [{ mistake: '45÷6=7.5', reason: '倍数-1概念不清', correction: '45÷5=9', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.3, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'diff-m-03', knowledgePoints: ['g3-diff-multiple'], type: 'fill', difficulty: 3,
    stem: '书架上层是下层的5倍，上层拿60本到下层则两层相等。原下层___本。', answer: '30',
    solution: [{ description: '上层比下层多60×2=120本，下=120÷4=30' }], hints: ['移多少则差2倍'],
    commonMistakes: [{ mistake: '60÷4=15', reason: '忽略移后差为2倍', correction: '120÷4=30', errorLayer: 'L3' }],
    irtParams: { a: 1.3, b: 0.8, c: 0.2 }, estimatedTime: 120 }),
  // g3-sum-diff 和差问题
  mk({ id: 'sum-d-01', knowledgePoints: ['g3-sum-diff'], type: 'choice', difficulty: 1,
    stem: '两数之和为30，两数之差为10。较大数是？', options: ['10','15','20','25'], answer: '2',
    solution: [{ description: '大数=(30+10)÷2=20' }], hints: ['大数=(和+差)÷2','小数=(和-差)÷2'],
    commonMistakes: [{ mistake: '30÷2=15', reason: '未利用差', correction: '(30+10)÷2=20', errorLayer: 'L2' }],
    irtParams: { a: 1, b: -0.3, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'sum-d-02', knowledgePoints: ['g3-sum-diff'], type: 'fill', difficulty: 2,
    stem: '两数之和为64，两数之差为18。大数=___，小数=___。', answer: '41',
    solution: [{ description: '大数=(64+18)÷2=41，小数=23' }], hints: ['大数=(和+差)÷2'],
    commonMistakes: [{ mistake: '64+18=82,82÷2=41但小数算错', reason: '计算错误', correction: '41,23', errorLayer: 'L3' }],
    irtParams: { a: 1.2, b: 0.5, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'sum-d-03', knowledgePoints: ['g3-sum-diff'], type: 'fill', difficulty: 3,
    stem: '语文和数学平均90分，数学比语文多8分。数学=___分。', answer: '94',
    solution: [{ description: '总分=180，数学=(180+8)÷2=94' }], hints: ['总分=平均×2'],
    commonMistakes: [{ mistake: '90+8=98', reason: '误把平均当某科分数', correction: '180+8后÷2', errorLayer: 'L3' }],
    irtParams: { a: 1.3, b: 0.6, c: 0.2 }, estimatedTime: 120 }),
  // g3-arithmetic-seq 等差数列
  mk({ id: 'arith-01', knowledgePoints: ['g3-arithmetic-seq'], type: 'choice', difficulty: 1,
    stem: '等差数列2,5,8,11,...的第10项是？', options: ['26','29','32','35'], answer: '1',
    solution: [{ description: '2+(10-1)×3=29' }], hints: ['第n项=首项+(n-1)×公差'],
    commonMistakes: [{ mistake: '2+10×3=32', reason: '用n而非n-1', correction: '2+9×3=29', errorLayer: 'L2' }],
    irtParams: { a: 1, b: -0.2, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'arith-02', knowledgePoints: ['g3-arithmetic-seq'], type: 'fill', difficulty: 2,
    stem: '等差数列1,4,7,10,...前10项之和是___。', answer: '145',
    solution: [{ description: '末项=1+9×3=28，和=(1+28)×10÷2=145' }], hints: ['先求末项','和=(首+末)×项数÷2'],
    commonMistakes: [{ mistake: '(1+28)×10=290', reason: '忘÷2', correction: '290÷2=145', errorLayer: 'L3' }],
    irtParams: { a: 1.2, b: 0.4, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'arith-03', knowledgePoints: ['g3-arithmetic-seq'], type: 'fill', difficulty: 3,
    stem: '等差数列首项3，末项48，和为255。项数=___，公差=___。', answer: '10',
    solution: [{ description: '项数=2×255÷(3+48)=10，公差=(48-3)÷9=5' }],
    hints: ['项数=2×和÷(首+末)','公差=(末-首)÷(项数-1)'],
    commonMistakes: [{ mistake: '项数=255÷(3+48)', reason: '未×2', correction: '510÷51=10', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1.1, c: 0.2 }, estimatedTime: 150 }),
  // g3-plant 植树问题
  mk({ id: 'plant-01', knowledgePoints: ['g3-plant'], type: 'choice', difficulty: 1,
    stem: '小路长30米，每5米种1棵，两端都种。共多少棵？', options: ['5','6','7','8'], answer: '2',
    solution: [{ description: '间隔=30÷5=6，棵数=6+1=7' }], hints: ['两端都种→棵数=间隔+1'],
    commonMistakes: [{ mistake: '30÷5=6', reason: '未+1', correction: '6+1=7', errorLayer: 'L1' }],
    irtParams: { a: 1, b: -0.5, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'plant-02', knowledgePoints: ['g3-plant'], type: 'fill', difficulty: 2,
    stem: '圆形花园周长48米，每4米种1株花。共___株。', answer: '12',
    solution: [{ description: '封闭图形：棵数=间隔=48÷4=12' }], hints: ['封闭：棵数=间隔'],
    commonMistakes: [{ mistake: '48÷4+1=13', reason: '混淆直线与环形', correction: '48÷4=12', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.3, c: 0.2 }, estimatedTime: 60 }),
  mk({ id: 'plant-03', knowledgePoints: ['g3-plant'], type: 'fill', difficulty: 3,
    stem: '一座桥长200米，两侧栏杆每2米插1面旗，两端都插。共___面旗。', answer: '202',
    solution: [{ description: '一侧=200÷2+1=101，两侧=202' }], hints: ['两侧需×2'],
    commonMistakes: [{ mistake: '101', reason: '忘×2', correction: '101×2=202', errorLayer: 'L2' }],
    irtParams: { a: 1.3, b: 0.6, c: 0.2 }, estimatedTime: 90 }),
  // g3-age 年龄问题
  mk({ id: 'age-01', knowledgePoints: ['g3-age'], type: 'choice', difficulty: 1,
    stem: '爸爸今年36岁，儿子12岁。几年前爸爸是儿子的5倍？', options: ['3','6','9','12'], answer: '1',
    solution: [{ description: '差=24，24÷(5-1)=6，12-6=6年前' }], hints: ['年龄差不变'],
    commonMistakes: [{ mistake: '36÷5=7.2', reason: '不会用差倍', correction: '用差=24求', errorLayer: 'L3' }],
    irtParams: { a: 1.1, b: 0.3, c: 0.25 }, estimatedTime: 90 }),
  mk({ id: 'age-02', knowledgePoints: ['g3-age'], type: 'fill', difficulty: 2,
    stem: '妈妈比小明大28岁，3年后妈妈是小明的5倍。小明今年___岁。', answer: '4',
    solution: [{ description: '3年后：28÷4=7岁，今年=7-3=4' }], hints: ['3年后差仍28'],
    commonMistakes: [{ mistake: '28÷5=5.6', reason: '忘倍数-1', correction: '28÷4=7', errorLayer: 'L3' }],
    irtParams: { a: 1.3, b: 0.7, c: 0.2 }, estimatedTime: 120 }),
  mk({ id: 'age-03', knowledgePoints: ['g3-age'], type: 'fill', difficulty: 3,
    stem: '甲今年18岁，乙12岁，丙8岁。___年前甲的年龄等于乙丙年龄和。', answer: '2',
    solution: [{ description: '设x年前：18-x=12-x+8-x → x=2' }], hints: ['每人每年少1岁'],
    commonMistakes: [{ mistake: '列方程忘乙丙都少x', reason: '漏项', correction: '注意两人共少2x', errorLayer: 'L4' }],
    irtParams: { a: 1.4, b: 1.2, c: 0.2 }, estimatedTime: 150 }),
  // g4-chicken-rabbit 鸡兔同笼
  mk({ id: 'cr-01', knowledgePoints: ['g4-chicken-rabbit'], type: 'choice', difficulty: 1,
    stem: '笼中有鸡兔共10只，共有腿28条。兔有几只？', options: ['3','4','5','6'], answer: '1',
    solution: [{ description: '假设全是鸡：20条腿，多8条÷2=4只兔' }], hints: ['用假设法','多的腿=兔的只数×2'],
    commonMistakes: [{ mistake: '(28-10×2)÷4', reason: '除以4而非2', correction: '÷(4-2)=÷2', errorLayer: 'L2' }],
    irtParams: { a: 1.1, b: 0, c: 0.25 }, estimatedTime: 90 }),
  mk({ id: 'cr-02', knowledgePoints: ['g4-chicken-rabbit'], type: 'fill', difficulty: 2,
    stem: '2分和5分硬币共30枚，总值9角9分。5分硬币___枚。', answer: '13',
    solution: [{ description: '假设全是2分：60分，多39分÷3=13枚5分' }], hints: ['单位统一为分','多的÷(5-2)'],
    commonMistakes: [{ mistake: '99÷5=19.8', reason: '不会用假设法', correction: '(99-60)÷3=13', errorLayer: 'L3' }],
    irtParams: { a: 1.3, b: 0.5, c: 0.2 }, estimatedTime: 120 }),
  mk({ id: 'cr-03', knowledgePoints: ['g4-chicken-rabbit'], type: 'fill', difficulty: 4,
    stem: '数学竞赛共20题，对一题得5分，错一题倒扣3分。小明得60分。他对了___题。', answer: '15',
    solution: [{ description: '全对100分，少40分÷(5+3)=5错，对=15' }], hints: ['错一题差=5+3=8分'],
    commonMistakes: [{ mistake: '(100-60)÷5=8错', reason: '未用倒扣+原分差', correction: '40÷8=5', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1.3, c: 0.2 }, estimatedTime: 150 }),
  // g4-area-perimeter 面积周长
  mk({ id: 'ap-01', knowledgePoints: ['g4-area-perimeter'], type: 'choice', difficulty: 1,
    stem: '正方形边长6厘米，面积是多少？', options: ['24','30','36','42'], answer: '2',
    solution: [{ description: '面积=6×6=36cm²' }], hints: ['面积=边长²'],
    commonMistakes: [{ mistake: '6×4=24', reason: '混淆周长和面积', correction: '6×6=36', errorLayer: 'L1' }],
    irtParams: { a: 1, b: -0.3, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'ap-02', knowledgePoints: ['g4-area-perimeter'], type: 'fill', difficulty: 2,
    stem: '长方形长12cm，宽8cm。周长=___cm，面积=___cm²。', answer: '40',
    solution: [{ description: '周长=(12+8)×2=40，面积=96' }], hints: ['周长=2×(长+宽)'],
    commonMistakes: [{ mistake: '12×8=96当周长', reason: '混淆公式', correction: '(12+8)×2=40', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.3, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'ap-03', knowledgePoints: ['g4-area-perimeter'], type: 'fill', difficulty: 3,
    stem: '一个长方形面积72cm²，长比宽多6cm。长=___cm，宽=___cm。', answer: '12',
    solution: [{ description: '设宽x,长x+6：x(x+6)=72→x=6,长=12' }], hints: ['试因数8×9=72但差为1，再试12×6=72'],
    commonMistakes: [{ mistake: '乱试不设变量', reason: '思路不清', correction: '设x列方程', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1, c: 0.2 }, estimatedTime: 120 }),
  // g4-profit-loss 盈亏问题
  mk({ id: 'pl-01', knowledgePoints: ['g4-profit-loss'], type: 'choice', difficulty: 1,
    stem: '同学分糖：每人5颗多3颗；每人6颗少4颗。有多少同学？', options: ['5','6','7','8'], answer: '2',
    solution: [{ description: '人数=(3+4)÷(6-5)=7' }], hints: ['(盈+亏)÷两次分配差'],
    commonMistakes: [{ mistake: '(4-3)÷1=1', reason: '用盈-亏', correction: '盈+亏=7', errorLayer: 'L2' }],
    irtParams: { a: 1.1, b: 0.2, c: 0.25 }, estimatedTime: 90 }),
  mk({ id: 'pl-02', knowledgePoints: ['g4-profit-loss'], type: 'fill', difficulty: 2,
    stem: '小朋友分书：每人8本多12本；每人10本少8本。共___人，书共___本。', answer: '10',
    solution: [{ description: '人数=(12+8)÷2=10，书=8×10+12=92' }], hints: ['(盈+亏)÷差=人数'],
    commonMistakes: [{ mistake: '12-8=4÷2=2', reason: '盈-亏错误', correction: '(12+8)÷2=10', errorLayer: 'L2' }],
    irtParams: { a: 1.3, b: 0.6, c: 0.2 }, estimatedTime: 120 }),
  mk({ id: 'pl-03', knowledgePoints: ['g4-profit-loss'], type: 'fill', difficulty: 3,
    stem: '老师分笔：每人8支剩7支；每人9支少2支。共___人，共___支笔。', answer: '9',
    solution: [{ description: '人数=(7+2)÷(9-8)=9，笔=8×9+7=79' }], hints: ['(盈+亏)÷分配差=人数'],
    commonMistakes: [{ mistake: '7-2=5÷1=5', reason: '盈-亏错误', correction: '(7+2)÷1=9', errorLayer: 'L4' }],
    irtParams: { a: 1.4, b: 1.4, c: 0.2 }, estimatedTime: 150 }),
  // g5-fraction-split 分数裂项
  mk({ id: 'fs-01', knowledgePoints: ['g5-fraction-split'], type: 'choice', difficulty: 2,
    stem: '1/(1×2) + 1/(2×3) + 1/(3×4) + 1/(4×5) = ?', options: ['1/2','2/5','3/5','4/5'], answer: '3',
    solution: [{ description: '裂项:1-1/2+1/2-1/3+...-1/5=1-1/5=4/5' }], hints: ['1/n(n+1)=1/n-1/(n+1)'],
    commonMistakes: [{ mistake: '1/2+1/6+1/12+1/20=30/60+10/60+5/60+3/60=48/60', reason: '硬算易错', correction: '裂项抵消', errorLayer: 'L3' }],
    irtParams: { a: 1.2, b: 0.5, c: 0.25 }, estimatedTime: 90 }),
  mk({ id: 'fs-02', knowledgePoints: ['g5-fraction-split'], type: 'fill', difficulty: 3,
    stem: '1/(1×3)+1/(3×5)+1/(5×7)+1/(7×9)=___。', answer: '4/9',
    solution: [{ description: '裂项=1/2(1-1/3+1/3-1/5+...-1/9)=1/2×8/9=4/9' }], hints: ['1/n(n+2)=(1/2)(1/n-1/(n+2))'],
    commonMistakes: [{ mistake: '未提1/2', reason: '差=2需补1/2', correction: '提1/2', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1, c: 0.2 }, estimatedTime: 120 }),
  mk({ id: 'fs-03', knowledgePoints: ['g5-fraction-split'], type: 'fill', difficulty: 4,
    stem: '1/2+1/6+1/12+1/20+1/30=___。', answer: '5/6',
    solution: [{ description: '1/(1×2)+...+1/(5×6)=1-1/6=5/6' }], hints: ['改写分母为n(n+1)'],
    commonMistakes: [{ mistake: '1/2+1/6=2/3硬算', reason: '未识别裂项', correction: '1-1/6=5/6', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1.2, c: 0.2 }, estimatedTime: 120 }),
  // g5-simple-eq 简易方程
  mk({ id: 'eq-01', knowledgePoints: ['g5-simple-eq'], type: 'choice', difficulty: 1,
    stem: '解方程:3x+7=22，x=?', options: ['3','4','5','6'], answer: '2',
    solution: [{ description: '3x=15, x=5' }], hints: ['先移项','两边÷3'],
    commonMistakes: [{ mistake: '3x=22+7=29', reason: '移项不变号', correction: '3x=15', errorLayer: 'L2' }],
    irtParams: { a: 1, b: -0.1, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'eq-02', knowledgePoints: ['g5-simple-eq'], type: 'fill', difficulty: 2,
    stem: '解方程:5(x-3)=2x+6，x=___。', answer: '7',
    solution: [{ description: '5x-15=2x+6, 3x=21, x=7' }], hints: ['先去括号','移项合并同类项'],
    commonMistakes: [{ mistake: '5x-3=2x+6', reason: '漏乘-3', correction: '5x-15=2x+6', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.4, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'eq-03', knowledgePoints: ['g5-simple-eq'], type: 'fill', difficulty: 3,
    stem: '解方程:(x+4)/3 - (2x-1)/4 = 2，x=___。', answer: '-5/2',
    solution: [{ description: '×12: 4(x+4)-3(2x-1)=24 → 4x+16-6x+3=24 → -2x=5 → x=-5/2' }],
    hints: ['先去分母×12','注意负号'], commonMistakes: [{ mistake: '×12时符号错', reason: '漏负号', correction: '-3×(-1)=+3', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1.1, c: 0.2 }, estimatedTime: 150 }),
  // g5-fraction-add 分数加减法
  mk({ id: 'fa-01', knowledgePoints: ['g5-fraction-add'], type: 'choice', difficulty: 1,
    stem: '1/2 + 1/3 = ?', options: ['2/5','1/5','5/6','2/6'], answer: '2',
    solution: [{ description: '3/6+2/6=5/6' }], hints: ['通分分母6'],
    commonMistakes: [{ mistake: '1+1/2+3=2/5', reason: '分子分母直接加', correction: '通分', errorLayer: 'L1' }],
    irtParams: { a: 1, b: -0.2, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'fa-02', knowledgePoints: ['g5-fraction-add'], type: 'fill', difficulty: 2,
    stem: '3/4 - 2/3 + 5/6 = ___。', answer: '11/12',
    solution: [{ description: '9/12-8/12+10/12=11/12' }], hints: ['最小公分母12'],
    commonMistakes: [{ mistake: '3-2+5/4+3+6=6/13', reason: '不通分', correction: '通分后加减', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.3, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'fa-03', knowledgePoints: ['g5-fraction-add'], type: 'fill', difficulty: 3,
    stem: '2又3/4 + 1又5/6 - 3/8 = ___。', answer: '4又1/24',
    solution: [{ description: '11/4+11/6-3/8=66/24+44/24-9/24=101/24=4又5/24' }],
    hints: ['带分数化假分数','分母24'], commonMistakes: [{ mistake: '分数+整数分开计算错误', reason: '概念不清', correction: '统一为假分数', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 0.9, c: 0.2 }, estimatedTime: 120 }),
  // g6-number-theory 数论质数
  mk({ id: 'nt-01', knowledgePoints: ['g6-number-theory'], type: 'choice', difficulty: 1,
    stem: '下列哪个是质数？', options: ['9','15','21','23'], answer: '3',
    solution: [{ description: '23仅能被1和23整除' }], hints: ['质数只有1和自己两个因数'],
    commonMistakes: [{ mistake: '9=3×3也是质数', reason: '概念错误', correction: '9是合数', errorLayer: 'L1' }],
    irtParams: { a: 1, b: -0.4, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'nt-02', knowledgePoints: ['g6-number-theory'], type: 'fill', difficulty: 2,
    stem: '把60分解质因数:60=___。', answer: '2×2×3×5',
    solution: [{ description: '60=2×2×3×5' }], hints: ['从小到大除质数'],
    commonMistakes: [{ mistake: '60=4×3×5', reason: '4非质数', correction: '4=2×2', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.4, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'nt-03', knowledgePoints: ['g6-number-theory'], type: 'fill', difficulty: 3,
    stem: '一个数的最大因数是36，它的质因数和=___。', answer: '5',
    solution: [{ description: '此数是36，36=2²×3²，质因数和=2+3=5' }], hints: ['最大因数即自身'],
    commonMistakes: [{ mistake: '1+2+3+4+6+9+12+18+36', reason: '把因数当质因数', correction: '质因数只有2和3', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1.1, c: 0.2 }, estimatedTime: 120 }),
  // g6-geometry-model 几何蝴蝶
  mk({ id: 'gm-01', knowledgePoints: ['g6-geometry-model'], type: 'choice', difficulty: 2,
    stem: '梯形对角线分成4个三角形，上下两个面积分别为4和9。梯形面积=?', options: ['13','20','25','36'], answer: '2',
    solution: [{ description: '左右相等=√(4×9)=6，总面积=4+9+6+6=25' }], hints: ['蝴蝶模型:S左=S右=√(S上×S下)'],
    commonMistakes: [{ mistake: '4+9+13+13=39', reason: '未用√(S上×S下)', correction: '√36=6', errorLayer: 'L3' }],
    irtParams: { a: 1.3, b: 0.8, c: 0.25 }, estimatedTime: 90 }),
  mk({ id: 'gm-02', knowledgePoints: ['g6-geometry-model'], type: 'fill', difficulty: 3,
    stem: '梯形上底:下底=2:3，上三角形面积8。下三角形面积=___。', answer: '18',
    solution: [{ description: '上下相似，面积比=边长平方比=4:9，下=8×9/4=18' }], hints: ['相似三角形面积比=平方比'],
    commonMistakes: [{ mistake: '8×3/2=12', reason: '用一次比而非平方', correction: '×9/4=18', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1.2, c: 0.2 }, estimatedTime: 120 }),
  mk({ id: 'gm-03', knowledgePoints: ['g6-geometry-model'], type: 'fill', difficulty: 4,
    stem: '梯形ABCD中S△AOB=4，S△BOC=12。S△AOD=___。', answer: '12',
    solution: [{ description: '蝴蝶模型：S△AOD=S△BOC=12' }],
    hints: ['蝴蝶模型对角三角形面积相等'], commonMistakes: [{ mistake: '对角线面积不分', reason: '混淆', correction: '对角三角形面积相等', errorLayer: 'L3' }],
    irtParams: { a: 1.5, b: 1.5, c: 0.2 }, estimatedTime: 150 }),
  // g6-motion 行程问题
  mk({ id: 'mo-01', knowledgePoints: ['g6-motion'], type: 'choice', difficulty: 1,
    stem: '甲每小时6km，乙每小时4km，相向而行相距30km。几小时相遇？', options: ['2','3','4','5'], answer: '1',
    solution: [{ description: '30÷(6+4)=3小时' }], hints: ['相遇时间=距离÷速度和'],
    commonMistakes: [{ mistake: '30÷6=5', reason: '只用一个速度', correction: '÷速度和', errorLayer: 'L1' }],
    irtParams: { a: 1, b: 0, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'mo-02', knowledgePoints: ['g6-motion'], type: 'fill', difficulty: 2,
    stem: '甲每小时8km，乙每小时5km。甲在乙后，两人同向，乙先走3小时。甲追上乙需___小时。', answer: '5',
    solution: [{ description: '乙先走15km，15÷(8-5)=5小时' }], hints: ['追及时间=距离差÷速度差'],
    commonMistakes: [{ mistake: '15÷8', reason: '用甲速度', correction: '÷速度差', errorLayer: 'L2' }],
    irtParams: { a: 1.3, b: 0.6, c: 0.2 }, estimatedTime: 120 }),
  mk({ id: 'mo-03', knowledgePoints: ['g6-motion'], type: 'fill', difficulty: 4,
    stem: 'A、B两城相距480km。客车A到B每小时60km，货车B到A每小时40km。同时出发，相遇后又继续前进，各到对方城后立即返回。从出发到第二次相遇共___小时。', answer: '14.4',
    solution: [{ description: '共走3倍全程=1440km，1440÷(60+40)=14.4' }], hints: ['第二次相遇共走3AB'],
    commonMistakes: [{ mistake: '只走1倍AB', reason: '没理解往返', correction: '3×480=1440', errorLayer: 'L4' }],
    irtParams: { a: 1.5, b: 1.5, c: 0.2 }, estimatedTime: 180 }),
  // g6-circle 圆
  mk({ id: 'ci-01', knowledgePoints: ['g6-circle'], type: 'choice', difficulty: 1,
    stem: '圆半径7cm，周长约多少？(π取3.14)', options: ['22','44','154','43.96'], answer: '3',
    solution: [{ description: '2×3.14×7=43.96' }], hints: ['C=2πr'],
    commonMistakes: [{ mistake: '3.14×7²=153.86', reason: '混淆周长和面积', correction: '2πr', errorLayer: 'L1' }],
    irtParams: { a: 1, b: -0.3, c: 0.25 }, estimatedTime: 60 }),
  mk({ id: 'ci-02', knowledgePoints: ['g6-circle'], type: 'fill', difficulty: 2,
    stem: '圆直径20cm。周长=___cm，面积=___cm²。(π取3.14)', answer: '62.8',
    solution: [{ description: 'r=10, C=62.8, S=314' }], hints: ['r=d÷2'],
    commonMistakes: [{ mistake: 'd代r', reason: '直径当半径', correction: 'r=10', errorLayer: 'L2' }],
    irtParams: { a: 1.2, b: 0.4, c: 0.2 }, estimatedTime: 90 }),
  mk({ id: 'ci-03', knowledgePoints: ['g6-circle'], type: 'fill', difficulty: 3,
    stem: '大圆R=7cm，小圆r=5cm。环形面积=___cm²。(π取3.14)', answer: '75.36',
    solution: [{ description: '3.14×(49-25)=3.14×24=75.36' }], hints: ['S环=π(R²-r²)'],
    commonMistakes: [{ mistake: '3.14×(7-5)²', reason: '先差再平方', correction: '先平方再差', errorLayer: 'L3' }],
    irtParams: { a: 1.4, b: 1, c: 0.2 }, estimatedTime: 120 }),
]

export function findByKnowledge(kp: string): Exercise[] {
  return EXERCISE_POOL.filter(e => e.knowledgePoints.includes(kp))
}

export function randomPick(pool: Exercise[], count: number): Exercise[] {
  const copy = pool.slice()
  const out: Exercise[] = []
  for (let i = 0; i < count && copy.length > 0; i++) {
    const idx = Math.floor(Math.random() * copy.length)
    out.push(copy.splice(idx, 1)[0])
  }
  return out
}
